from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from ..logging_utils import get_logger
from ..strategies.base import StrategyDefinition

logger = get_logger(__name__)

BACKTESTS_DIR = Path(__file__).resolve().parent
RESULTS_DIR = BACKTESTS_DIR / "results"
RESULTS_DIR.mkdir(exist_ok=True)


@dataclass
class Trade:
    entry_time: pd.Timestamp
    exit_time: pd.Timestamp
    direction: str  # "long" or "short"
    entry_price: float
    exit_price: float
    stop_loss: float
    take_profit: float
    pnl: float


@dataclass
class BacktestResult:
    strategy: StrategyDefinition
    symbol: str
    timeframe: str
    trades: List[Trade]
    equity_curve: pd.Series  # indexed by time
    stats: Dict[str, float]

    def to_dict(self) -> Dict:
        return {
            "strategy": self.strategy.to_dict(),
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "trades": [t.__dict__ for t in self.trades],
            "equity_curve": self.equity_curve.to_dict(),
            "stats": self.stats,
        }


def _eval_rule(row: pd.Series, rule: str) -> bool:
    """Evaluate a simple boolean rule string against a row of features.

    SECURITY NOTE: this uses eval with a restricted namespace and only the
    row's values. Rules are generated by our own system, not user input.
    """
    local_vars = {k: float(row[k]) for k in row.index if isinstance(row[k], (int, float, np.floating))}
    try:
        return bool(eval(rule, {"__builtins__": {}}, local_vars))
    except Exception:
        return False


def run_backtest(
    df: pd.DataFrame,
    strategy: StrategyDefinition,
    initial_equity: float = 10_000.0,
    risk_per_trade_pct: float = 0.5,
    pip_size: Optional[float] = None,
) -> BacktestResult:
    """Very simple OHLC-based backtest for a single strategy.

    Assumes df contains columns: time, open, high, low, close, rsi, ma_short,
    ma_long, atr, volatility, trend_strength, etc.
    """
    logger.info(
        "Running backtest for %s on %s %s (len=%d)",
        strategy.name,
        strategy.symbol,
        strategy.timeframe,
        len(df),
    )

    df = df.copy().reset_index(drop=True)
    equity = initial_equity
    equity_curve = []
    times = []
    trades: List[Trade] = []

    position = None  # dict with entry info

    # crude pip size default: assume 0.01 for metals/indices, 0.0001 otherwise
    if pip_size is None:
        pip_size = 0.01 if "XAU" in strategy.symbol or "XAG" in strategy.symbol else 0.0001

    for i, row in df.iterrows():
        time = row["time"]
        close = float(row["close"])
        high = float(row["high"])
        low = float(row["low"])

        if position is None:
            # flat: check entry
            if _eval_rule(row, strategy.entry_rule):
                # risk sizing: risk_per_trade_pct of equity as distance to SL
                risk_amount = equity * (risk_per_trade_pct / 100.0)
                sl_distance = strategy.stop_loss_pips * pip_size
                if sl_distance <= 0:
                    continue
                # position size in units (simplified; not broker-accurate)
                size = risk_amount / sl_distance

                direction = "long" if "rsi <" in strategy.entry_rule or "trend_strength >" in strategy.entry_rule else "short"

                if direction == "long":
                    stop_loss = close - strategy.stop_loss_pips * pip_size
                    take_profit = close + strategy.take_profit_pips * pip_size
                else:
                    stop_loss = close + strategy.stop_loss_pips * pip_size
                    take_profit = close - strategy.take_profit_pips * pip_size

                position = {
                    "entry_time": time,
                    "entry_price": close,
                    "direction": direction,
                    "size": size,
                    "stop_loss": stop_loss,
                    "take_profit": take_profit,
                }
        else:
            # in position: check exit conditions and SL/TP
            exit_reason = None
            exit_price = close

            # SL/TP first
            if position["direction"] == "long":
                if low <= position["stop_loss"]:
                    exit_price = position["stop_loss"]
                    exit_reason = "stop_loss"
                elif high >= position["take_profit"]:
                    exit_price = position["take_profit"]
                    exit_reason = "take_profit"
            else:
                if high >= position["stop_loss"]:
                    exit_price = position["stop_loss"]
                    exit_reason = "stop_loss"
                elif low <= position["take_profit"]:
                    exit_price = position["take_profit"]
                    exit_reason = "take_profit"

            # rule-based exit
            if exit_reason is None and _eval_rule(row, strategy.exit_rule):
                exit_reason = "exit_rule"

            if exit_reason is not None:
                # compute PnL in currency
                if position["direction"] == "long":
                    pnl = (exit_price - position["entry_price"]) * position["size"]
                else:
                    pnl = (position["entry_price"] - exit_price) * position["size"]

                equity += pnl
                trades.append(
                    Trade(
                        entry_time=position["entry_time"],
                        exit_time=time,
                        direction=position["direction"],
                        entry_price=position["entry_price"],
                        exit_price=exit_price,
                        stop_loss=position["stop_loss"],
                        take_profit=position["take_profit"],
                        pnl=pnl,
                    )
                )
                position = None

        times.append(time)
        equity_curve.append(equity)

    equity_series = pd.Series(equity_curve, index=pd.to_datetime(times))

    stats = _compute_basic_stats(equity_series, trades, initial_equity)

    logger.info(
        "Backtest complete for %s: trades=%d, final_eq=%.2f, max_dd=%.2f%%",
        strategy.name,
        len(trades),
        equity,
        stats.get("max_drawdown_pct", 0.0),
    )

    return BacktestResult(
        strategy=strategy,
        symbol=strategy.symbol,
        timeframe=strategy.timeframe,
        trades=trades,
        equity_curve=equity_series,
        stats=stats,
    )


def _compute_basic_stats(
    equity_curve: pd.Series,
    trades: List[Trade],
    initial_equity: float,
) -> Dict[str, float]:
    if equity_curve.empty:
        return {"final_equity": initial_equity, "max_drawdown_pct": 0.0}

    final_equity = float(equity_curve.iloc[-1])
    returns = equity_curve.pct_change().dropna()

    # annualized Sharpe assuming 252 periods per year
    if not returns.empty:
        sharpe = float(np.sqrt(252) * returns.mean() / (returns.std() + 1e-9))
    else:
        sharpe = 0.0

    # max drawdown
    running_max = equity_curve.cummax()
    drawdowns = equity_curve / running_max - 1.0
    max_dd = float(drawdowns.min())

    # profit factor & win rate
    gains = [t.pnl for t in trades if t.pnl > 0]
    losses = [t.pnl for t in trades if t.pnl < 0]
    gross_profit = float(sum(gains)) if gains else 0.0
    gross_loss = float(-sum(losses)) if losses else 0.0
    profit_factor = gross_profit / (gross_loss + 1e-9) if gross_loss > 0 else 0.0

    win_rate = (len(gains) / len(trades)) if trades else 0.0

    return {
        "initial_equity": float(initial_equity),
        "final_equity": final_equity,
        "net_profit": final_equity - initial_equity,
        "return_pct": (final_equity - initial_equity) / initial_equity * 100.0,
        "sharpe_ratio": sharpe,
        "max_drawdown_pct": max_dd * 100.0,
        "profit_factor": profit_factor,
        "win_rate": win_rate,
        "num_trades": float(len(trades)),
    }


def save_backtest_result(result: BacktestResult) -> Path:
    path = RESULTS_DIR / f"{result.strategy.name}_{result.symbol}_{result.timeframe}.json"
    import json

    with path.open("w", encoding="utf-8") as f:
        json.dump(result.to_dict(), f, indent=2, default=str)
    logger.info("Saved backtest result to %s", path)
    return path
